### ISSUE TITLE
Potental stack allocation bug

### ISSUE THREAD

**Issue by YangZhou1997** [shenango/caladan#14]
Hi Caladan authors! 

I just tried to print out each uthread's stack address and find they are generally 0x7ffff... However, based on the [variable](https://github.com/shenango/caladan/blob/1ab795053531dacf6bde366471a4439ae72313c4/runtime/stack.c#L16) 
 of STACK_BASE_ADDR, stack address should start from 0x2000... Then I find this [line](https://github.com/shenango/caladan/blob/1ab795053531dacf6bde366471a4439ae72313c4/runtime/stack.c#L83) actually calls atomic64_fetch_and_**and**() instead of atomic64_fetch_and_**add**(). So it seems this is a small typo? 

Just want to let you know about this potential bug, although the runtime works perfectly without fixing it! 

Best,
Yang

**Comment by joshuafried** [comment]
Thanks for pointing this out! We will remove the stack address hint code since we don't really need it.
