### ISSUE TITLE
"Floating point exception" when running synthetic app client

### ISSUE THREAD

**Issue by andreybleme** [shenango/caladan#27]
Hi all, 

I'm getting a "Floating point exception" when running the synthetic app client on a xl170 Cloudlab machine (https://docs.cloudlab.us/hardware.html):

```
$ sudo ./apps/synthetic/target/release/synthetic 128.110.218.122:5000 --config client.config --mode runtime-client

Floating point exception

$ sudo ./apps/synthetic/target/release/synthetic

Floating point exception
```

It happens regardless of the server IP, config file, or runtime mode (client and server fails), meaning that the packets are not even sent. Something is wrong with the synthetic app. 

Is there anything I can do to help fixing this?

I'm using the latest version from main branch (https://github.com/shenango/caladan/commit/d6fa6126a16d8d56e06ccbefdb815bcfe2d48313).

Thank you!

**Comment by joshuafried** [comment]
Hi - I just pushed a fix for this issue. Please let us know if it doesn't work or if there are any subsequent issues.

**Comment by andreybleme** [comment]
Thanks a lot @joshuafried 🎉 
Issue is fixed.
